joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0
  extra_joints:
    - name: 'rim_front_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'rim_front_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'rim_back_left_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
    - name: 'rim_back_right_joint'
      position: 0.0
      velocity: 0.0
      effort:   0.0
